dist: trusty
sudo: required
before_install:
  - sudo apt -qq update
  - sudo apt install -y virtualbox vagrant
  - vagrant init freebsd/FreeBSD-11.1-RELEASE --box-version 2017.07.21
  - vagrant up
  - vagrant ssh
